version: '3'

services: 

  nodejs:
    build: 
      context: ./nodejs
      dockerfile: Dockerfile
    image: renatobareira/nodejs:prod
    container_name: nodejs
    networks: 
      - nodenet

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: renatobareira/nginx:prod
    container_name: nginx
    networks: 
      - nodenet
    ports: 
      - "8080:80"
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nodenet    

networks: 
  nodenet:
    driver: bridge      