version: '3'

services: 

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
             --init-file /data/application/init.sql
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nodenet 
         
  nodejs:
    build: 
      context: ./nodejs
      dockerfile: Dockerfile
    image: renatobareira/nodejs:prod
    container_name: nodejs
    command: dockerize -wait tcp://db:3306 
             node index.js
    networks: 
      - nodenet
    depends_on:
      - db
    
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: renatobareira/nginx:prod
    container_name: nginx    
    networks: 
      - nodenet
    ports: 
      - "8080:80"
    depends_on:
      - nodejs

networks: 
  nodenet:
    driver: bridge      